version: "3"

services:
  db:
    image: postgres:13.4

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  api:
    build:
      dockerfile: api.Dockerfile.dev
      context: .

    ports:
      - 8085:8085

    depends_on:
      - db

    entrypoint: ./init.sh
