version: "3"

services:
  db:
    image: postgres:13.4

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5490:5432

    volumes:
      - /home/breno/.data/animelist:/var/lib/postgresql/data

  api:
    env_file:
      - compose.env

    build:
      dockerfile: api.Dockerfile.dev
      context: .

    ports:
      - 8085:8085

    depends_on:
      - db

    entrypoint: ["sh", "./init.sh"]
